In [1]:
# Подключаем библиотеки
import pandas as pd # Работа с набором данных
import numpy as np # Линейная алгебра
# Визуализация данных
import seaborn as sns
import matplotlib.pyplot as plt

# отключение информационных сообщений
from warnings import filterwarnings
filterwarnings(action='ignore')

# разделение выборки
from sklearn.model_selection import train_test_split
#метрики
from sklearn import metrics
#Наивный байесовский классификатор
from sklearn.naive_bayes import GaussianNB

In [2]:
fl = 'готовая табла .xlsx'
data = pd.read_excel(fl)
data.head(5)

STG   SCG   STR   LPR   PEG       UNS
0  0.00  0.00  0.00  0.00  0.00  very_low
1  0.08  0.08  0.10  0.24  0.90      High
2  0.06  0.06  0.05  0.25  0.33       Low
3  0.10  0.10  0.15  0.65  0.30    Middle
4  0.08  0.08  0.08  0.98  0.24       Low

In [3]:
data = data.rename(columns={' UNS': 'UNS'})

In [4]:
train, test = train_test_split(data, test_size = 0.4, stratify = data['UNS'], random_state = 42)

In [5]:
X_train = train[['STG','SCG', 'STR', 'LPR','PEG']]
y_train = train.UNS
X_test = test[['STG','SCG', 'STR', 'LPR','PEG']]
y_test = test.UNS

fn = ['STG','SCG', 'STR', 'LPR','PEG']
cn = data['UNS'].unique()

In [6]:
mod_gnb_all = GaussianNB()
y_pred = mod_gnb_all.fit(X_train, y_train).predict(X_test)

In [7]:

y_pred=mod_gnb_all.predict(X_test)

print('accuracy (точность) классификатора ',metrics.accuracy_score(y_pred,y_test))

print("матрица ошибок")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy (точность) классификатора  0.845679012345679
матрица ошибок
[[36  0  5  0  0]
 [ 0 51  0  0  1]
 [ 0 10 39  0  0]
 [ 0  1  0  8  1]
 [ 0  3  0  4  3]]


In [8]:
# Использование построенной модели для предсказания класса
new_blood=[0.07, 0.10, 0.14, 0.66, 0.31]
y_new_blood=mod_gnb_all.predict([new_blood])

print(y_new_blood)

['Low']
